//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 12:14:17 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cisco.com/cmad/rogastis", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cisco.cmad.rogastis.api;
